[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["github_issue_to_gsheet"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Webhook","Category/Integration","Internal/http"]
  name = "github_issue_to_gsheet"
  org = "hwjsk"
  version = "3.1.0"

